debug: false
spring.application.name: pub-demo-app
logging.level.root: INFO
server:
  port: 10000
spring:
  cloud:
    stream:
      function:
        definition: sendTestData
      bindings:
        sendTestData-out-0:
          destination: dataIn4
          binder: kafka1
      binders:
          kafka1:
            type: kafka
            environment:
              spring:
                cloud:
                  stream:
                    kafka:
                      binder:
                        brokers: ${kafka.brokers}
                        zkNodes: ${zk1}

kafka.brokers: localhost:9092
zk1: localhost:2181